version: '3'

services:
  shingo-affiliates-api:
    image: docker.shingo.org/shingo-affiliates-api
    build: .
    environment:
      NODE_ENV: production
      SF_API: "${SF_API:-shingo-sf-api}"
      AUTH_API: "${AUTH_API:-shingo-auth-api}"
      SHINGO_REDIS: "${SHINGO_REDIS:-shingo-redis}"
      EMAIL_PASS: "${EMAIL_PASS:?Must set EMAIL_PASS}"