version: '2.1'

services:
  shingo-affiliates-api:
    image: shingo-affiliates-api
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 80:80
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js